## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'keysight'

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_keysight'
description = 'Set of PyMoDAQ plugins for Keysight Instruments'

author = 'Sebastien J. Weber'
author-email = 'sebastien.weber@cnrs.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pyvisa']
